### ISSUE TITLE
print remaining cannon shots doesn't seem to be working

### ISSUE THREAD

**Issue by danielw97** [PsudoDeSudo/Toastush#2]
Hi there,
I dropped a message about this on discord, although figure it may be better here so we can potentially discuss.
Currently, the print remaining cannon shots option in ship configuration doesn't seem to be working.
I've tested in a weapon room on  a mission, and am not sure what's up with this.
I'm happy to troubleshoot this if there is anything in particular you would like me to try, currently running latest version of toastush along with proxiani 2.3.25.
Screenreader is nvda.
Thanks.

**Comment by PsudoDeSudo** [comment]
Thanks for reporting. I’ll take a look. Sent from Mail for Windows From: danielw97Sent: Sunday, September 1, 2024 5:17 PMTo: PsudoDeSudo/ToastushCc: SubscribedSubject: [PsudoDeSudo/Toastush] print remaining cannon shots doesn't seem to be working (Issue #2) Hi there,I dropped a message about this on discord, although figure it may be better here so we can potentially discuss.Currently, the print remaining cannon shots option in ship configuration doesn't seem to be working.I've tested in a weapon room on a mission, and am not sure what's up with this.I'm happy to troubleshoot this if there is anything in particular you would like me to try, currently running latest version of toastush along with proxiani 2.3.25.Screenreader is nvda.Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by danielw97** [comment]
Thanks for fixing this so quickly, a quick test suggests that it is working correctly now.
